name: Reddit Tracker (manual + Pacific midnight)

on:
  schedule:
    # - cron: "0 7 * * *"   # 07:00 UTC ~ midnight PT in PDT
    - cron: "0 8 * * *"   # 08:00 UTC ~ midnight PT in PST
  workflow_dispatch: {}    # manual runs

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current time (UTC & PT)
        run: |
          echo "UTC now: $(date -u '+%Y-%m-%d %H:%M:%S %Z')"
          TZ=America/Los_Angeles date '+PT  now: %Y-%m-%d %H:%M:%S %Z'

      # Decide whether to proceed:
      # - Always proceed for manual runs
      # - For scheduled runs, only proceed if local PT hour is 00
      - name: Decide gate
        id: decide
        shell: bash
        run: |
          export TZ=America/Los_Angeles
          HOUR="$(date '+%H')"
          if [ "${GITHUB_EVENT_NAME}" = "workflow_dispatch" ] || [ "${HOUR}" = "00" ]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
          else
            echo "run=false" >> "$GITHUB_OUTPUT"
          fi
          echo "Local PT hour=${HOUR}; event=${GITHUB_EVENT_NAME}"

      - name: Install dependencies
        if: steps.decide.outputs.run == 'true'
        working-directory: reddit_tracker
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python3 -m pip install -r requirements.txt
          else
            python3 -m pip install praw pandas python-dotenv
          fi

      - name: Auth smoke test (prints your Reddit user)
        if: steps.decide.outputs.run == 'true'
        working-directory: reddit_tracker
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          python3 - <<'PY'
          import os, praw
          r = praw.Reddit(
              client_id=os.environ["REDDIT_CLIENT_ID"],
              client_secret=os.environ["REDDIT_CLIENT_SECRET"],
              username=os.environ["REDDIT_USERNAME"],
              password=os.environ["REDDIT_PASSWORD"],
              user_agent=os.environ["REDDIT_USER_AGENT"],
          )
          print("Authenticated user:", r.user.me())
          PY

      - name: Run tracker
        if: steps.decide.outputs.run == 'true'
        working-directory: reddit_tracker
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          python3 -u reddit_post_tracker.py

      - name: Record timestamp
        if: steps.decide.outputs.run == 'true'
        working-directory: reddit_tracker
        run: |
          mkdir -p reddit_metrics
          echo "UTC: $(date -u '+%Y-%m-%d %H:%M:%S %Z')" > reddit_metrics/last_run_time.txt
          TZ=America/Los_Angeles date '+PT:  %Y-%m-%d %H:%M:%S %Z' >> reddit_metrics/last_run_time.txt
          echo "MODE: $([ "${GITHUB_EVENT_NAME}" = "workflow_dispatch" ] && echo manual || echo scheduled)" >> reddit_metrics/last_run_time.txt

      - name: Commit outputs
        if: steps.decide.outputs.run == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update reddit metrics"
          file_pattern: |
            reddit_tracker/reddit_metrics/*.csv
            reddit_tracker/reddit_metrics/last_run_time.txt



