name: Reddit Tracker (PST midnight + manual)

on:
  schedule:
    - cron: "0 8 * * *"   # 08:00 UTC == 00:00 PST
  workflow_dispatch:      # allow manual runs (bypass gate)

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print current time (UTC & PT)
        run: |
          echo "UTC now: $(date -u '+%Y-%m-%d %H:%M:%S %Z')"
          TZ=America/Los_Angeles date '+PT now: %Y-%m-%d %H:%M:%S %Z'

      # Decide if it's PST midnight (manual runs bypass later)
      - name: Decide gate
        id: decide
        run: |
          export TZ=America/Los_Angeles
          HOUR="$(date '+%H')"
          ZONE="$(date '+%Z')"     # 'PST' in winter; 'PDT' in summer
          echo "Local PT hour=$HOUR zone=$ZONE"
          echo "hour=$HOUR" >> "$GITHUB_OUTPUT"
          echo "zone=$ZONE" >> "$GITHUB_OUTPUT"

      - name: Set up Python 3.11
        if: ${{ github.event_name == 'workflow_dispatch' || (steps.decide.outputs.hour == '00' && steps.decide.outputs.zone == 'PST') }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        if: ${{ github.event_name == 'workflow_dispatch' || (steps.decide.outputs.hour == '00' && steps.decide.outputs.zone == 'PST') }}
        working-directory: reddit_tracker
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install praw pandas python-dotenv
          fi

      - name: Run tracker
        if: ${{ github.event_name == 'workflow_dispatch' || (steps.decide.outputs.hour == '00' && steps.decide.outputs.zone == 'PST') }}
        working-directory: reddit_tracker
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: python -u reddit_post_tracker.py

      - name: Record timestamps
        if: ${{ github.event_name == 'workflow_dispatch' || (steps.decide.outputs.hour == '00' && steps.decide.outputs.zone == 'PST') }}
        working-directory: reddit_tracker
        run: |
          mkdir -p reddit_metrics
          echo "UTC: $(date -u '+%Y-%m-%d %H:%M:%S %Z')" > reddit_metrics/last_run_time.txt
          TZ=America/Los_Angeles date '+PT: %Y-%m-%d %H:%M:%S %Z' >> reddit_metrics/last_run_time.txt

      - name: Commit outputs
        if: ${{ github.event_name == 'workflow_dispatch' || (steps.decide.outputs.hour == '00' && steps.decide.outputs.zone == 'PST') }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update reddit metrics"
          file_pattern: |
            reddit_tracker/reddit_metrics/*.csv
            reddit_tracker/reddit_metrics/last_run_time.txt
