name: Reddit Tracker (midnight PT + manual test)

on:
  schedule:
    # UTC cron; we gate to only run at 00:00 PT
    - cron: "0 8 * * *"   # PST midnight
  workflow_dispatch: {}    # manual runs should also update files

permissions:
  contents: write

concurrency:
  group: reddit-tracker
  cancel-in-progress: true

# your code lives in reddit_tracker/
defaults:
  run:
    working-directory: reddit_tracker

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show current time (UTC & PT)
        run: |
          echo "UTC now: $(date -u '+%Y-%m-%d %H:%M:%S %Z')"
          TZ=America/Los_Angeles date '+PT now: %Y-%m-%d %H:%M:%S %Z'

      # Gate logs midnight PT; manual runs will bypass in later steps
      - name: Gate on Pacific midnight
        id: gate
        run: |
          export TZ=America/Los_Angeles
          now="$(date '+%Y-%m-%d %H:%M:%S %Z')"
          hour="$(date '+%H')"
          echo "Local PT time: $now"
          if [ "$hour" = "00" ]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
          else
            echo "run=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Note manual bypass
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "Manual run detected — bypassing PT gate and executing all steps."

      - name: Set up Python
        if: ${{ steps.gate.outputs.run == 'true' || github.event_name == 'workflow_dispatch' }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        if: ${{ steps.gate.outputs.run == 'true' || github.event_name == 'workflow_dispatch' }}
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install praw pandas python-dotenv
          fi

      - name: Run tracker
        if: ${{ steps.gate.outputs.run == 'true' || github.event_name == 'workflow_dispatch' }}
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          python reddit_post_tracker.py

      - name: Record timestamps to file
        if: ${{ steps.gate.outputs.run == 'true' || github.event_name == 'workflow_dispatch' }}
        run: |
          mkdir -p reddit_metrics
          echo "UTC: $(date -u '+%Y-%m-%d %H:%M:%S %Z')" > reddit_metrics/last_run_time.txt
          TZ=America/Los_Angeles date '+PT: %Y-%m-%d %H:%M:%S %Z' >> reddit_metrics/last_run_time.txt
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "MODE: manual test" >> reddit_metrics/last_run_time.txt
          else
            echo "MODE: scheduled" >> reddit_metrics/last_run_time.txt
          fi

      - name: Commit CSVs and timestamp
        if: ${{ steps.gate.outputs.run == 'true' || github.event_name == 'workflow_dispatch' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ github.event_name == 'workflow_dispatch'
            && 'chore: update reddit metrics (manual test)'
            || 'chore: update reddit metrics (midnight PT)' }}
          file_pattern: |
            reddit_tracker/reddit_metrics/*.csv
            reddit_tracker/reddit_metrics/last_run_time.txt


