name: Reddit Tracker (PST midnight only + debug)

on:
  schedule:
    - cron: "0 8 * * *"   # 00:00 PST == 08:00 UTC
  workflow_dispatch: {}    # manual runs should also update files

permissions:
  contents: write

concurrency:
  group: reddit-tracker
  cancel-in-progress: true

# code is in the subfolder
defaults:
  run:
    working-directory: reddit_tracker

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show current time (UTC & PT)
        run: |
          echo "UTC now: $(date -u '+%Y-%m-%d %H:%M:%S %Z')"
          TZ=America/Los_Angeles date '+PT now: %Y-%m-%d %H:%M:%S %Z'

      # Gate: only midnight AND zone must be PST; manual runs bypass below
      - name: Gate on PST midnight only
        id: gate
        run: |
          export TZ=America/Los_Angeles
          now="$(date '+%Y-%m-%d %H:%M:%S %Z')"
          hour="$(date '+%H')"
          zone="$(date '+%Z')"
          echo "Local PT time: $now"
          echo "Detected zone: $zone"
          if [ "$hour" = "00" ] && [ "$zone" = "PST" ]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
          else
            echo "run=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Manual bypass note
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "Manual run -> bypassing PST gate."

      - name: Sanity: list repo tree
        if: ${{ steps.gate.outputs.run == 'true' || github.event_name == 'workflow_dispatch' }}
        run: |
          echo "=== Repo root ==="
          ls -la ..
          echo "=== reddit_tracker/ ==="
          ls -la .
          echo "=== reddit_tracker/reddit_metrics/ (before run) ==="
          ls -la reddit_metrics || true

      - name: Set up Python
        if: ${{ steps.gate.outputs.run == 'true' || github.event_name == 'workflow_dispatch' }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Python & pip versions
        if: ${{ steps.gate.outputs.run == 'true' || github.event_name == 'workflow_dispatch' }}
        run: |
          python -V
          python -m pip -V

      - name: Install dependencies
        if: ${{ steps.gate.outputs.run == 'true' || github.event_name == 'workflow_dispatch' }}
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          else
            python -m pip install --upgrade pip
            pip install praw pandas python-dotenv
          fi
          python - << 'PY'
import pkgutil, sys
mods = ["praw","pandas","dotenv"]
print("Installed modules:")
for m in mods:
    print(f" - {m}:",
          "OK" if pkgutil.find_loader(m) else "MISSING")
PY

      - name: Sanity: check secrets are present (masked)
        if: ${{ steps.gate.outputs.run == 'true' || github.event_name == 'workflow_dispatch' }}
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          echo "Has CLIENT_ID? $([ -n "${REDDIT_CLIENT_ID}" ] && echo yes || echo no)"
          echo "Has CLIENT_SECRET? $([ -n "${REDDIT_CLIENT_SECRET}" ] && echo yes || echo no)"
          echo "Username: ${REDDIT_USERNAME}"
          echo "Has PASSWORD? $([ -n "${REDDIT_PASSWORD}" ] && echo yes || echo no)"
          echo "User-Agent: ${REDDIT_USER_AGENT}"

      - name: Run tracker (with traceback)
        if: ${{ steps.gate.outputs.run == 'true' || github.event_name == 'workflow_dispatch' }}
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          set -euxo pipefail
          python -u reddit_post_tracker.py

      - name: Record timestamps to file
        if: ${{ steps.gate.outputs.run == 'true' || github.event_name == 'workflow_dispatch' }}
        run: |
          mkdir -p reddit_metrics
          echo "UTC: $(date -u '+%Y-%m-%d %H:%M:%S %Z')" > reddit_metrics/last_run_time.txt
          TZ=America/Los_Angeles date '+PT: %Y-%m-%d %H:%M:%S %Z' >> reddit_metrics/last_run_time.txt
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "MODE: manual test" >> reddit_metrics/last_run_time.txt
          else
            echo "MODE: scheduled (PST-only)" >> reddit_metrics/last_run_time.txt
          fi

      - name: Commit CSVs and timestamp (manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update reddit metrics (manual test)"
          file_pattern: |
            reddit_tracker/reddit_metrics/*.csv
            reddit_tracker/reddit_metrics/last_run_time.txt

      - name: Commit CSVs and timestamp (scheduled PST midnight)
        if: ${{ github.event_name != 'workflow_dispatch' && steps.gate.outputs.run == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update reddit metrics (PST midnight)"
          file_pattern: |
            reddit_tracker/reddit_metrics/*.csv
            reddit_tracker/reddit_metrics/last_run_time.txt





